name: Release
on:
  push:
    tags:
        - v*
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install node modules
        run: npm install
      - name: Build Library
        run: npm run build_lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_id }}.${{github.run_number}}.${{github.run_attempt}}
        run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes