name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm ci
        npm run build

    - name: Deploy
      if: success()
      uses: 3si-khanhnv/angular-github-actions@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true
