name: Create npm package
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[0-9a-z]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@3si-khanhnv"
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - run: npm run publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}