name: Release

on:
  push:
    tags:
        - "v*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: 3si-khanhnv/angular-github-actions@lastest
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false